version: '3'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./redis-volume:/data
    command: redis-server --save 20 1
  api:
    build:
      dockerfile: Dockerfile
      context: ./Web
    ports:
      - '5000:80'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
